export const groupA = [
  {
    name: "Katar",
    rank: 51,
    points: 0,
    goalsScored: 0,
    goalsConceded: 0,
    goalDifference: 0,
    win: 0,
    draw: 0,
    loss: 0,
    groupIndex: 1,
    teamIndex: 1,
  },
  {
    name: "Ekvador",
    rank: 46,
    points: 0,
    goalsScored: 0,
    goalsConceded: 0,
    goalDifference: 0,
    win: 0,
    draw: 0,
    loss: 0,
    groupIndex: 1,
    teamIndex: 2,
  },
  {
    name: "Senegal",
    rank: 20,
    points: 0,
    goalsScored: 0,
    goalsConceded: 0,
    goalDifference: 0,
    win: 0,
    draw: 0,
    loss: 0,
    groupIndex: 1,
    teamIndex: 3,
  },
  {
    name: "Holandija",
    rank: 10,
    points: 0,
    goalsScored: 0,
    goalsConceded: 0,
    goalDifference: 0,
    win: 0,
    draw: 0,
    loss: 0,
    groupIndex: 1,
    teamIndex: 4,
  },
];

export const groupB = [
  {
    name: "Engleska",
    rank: 5,
    points: 0,
    goalsScored: 0,
    goalsConceded: 0,
    goalDifference: 0,
    win: 0,
    draw: 0,
    loss: 0,
    groupIndex: 2,
    teamIndex: 5,
  },
  {
    name: "Iran",
    rank: 21,
    points: 0,
    goalsScored: 0,
    goalsConceded: 0,
    goalDifference: 0,
    win: 0,
    draw: 0,
    loss: 0,
    groupIndex: 2,
    teamIndex: 6,
  },
  {
    name: "SAD",
    rank: 15,
    points: 0,
    goalsScored: 0,
    goalsConceded: 0,
    goalDifference: 0,
    win: 0,
    draw: 0,
    loss: 0,
    groupIndex: 2,
    teamIndex: 7,
  },
  {
    name: "Ukrajina",
    rank: 27,
    points: 0,
    goalsScored: 0,
    goalsConceded: 0,
    goalDifference: 0,
    win: 0,
    draw: 0,
    loss: 0,
    groupIndex: 2,
    teamIndex: 8,
  },
];

export const groupC = [
  {
    name: "Argentina",
    rank: 4,
    points: 0,
    goalsScored: 0,
    goalsConceded: 0,
    goalDifference: 0,
    win: 0,
    draw: 0,
    loss: 0,
    groupIndex: 3,
    teamIndex: 9,
  },
  {
    name: "Saudijska Arabija",
    rank: 49,
    points: 0,
    goalsScored: 0,
    goalsConceded: 0,
    goalDifference: 0,
    win: 0,
    draw: 0,
    loss: 0,
    groupIndex: 3,
    teamIndex: 10,
  },
  {
    name: "Meksiko",
    rank: 9,
    points: 0,
    goalsScored: 0,
    goalsConceded: 0,
    goalDifference: 0,
    win: 0,
    draw: 0,
    loss: 0,
    groupIndex: 3,
    teamIndex: 11,
  },
  {
    name: "Poljska",
    rank: 10,
    points: 0,
    goalsScored: 0,
    goalsConceded: 0,
    goalDifference: 0,
    win: 0,
    draw: 0,
    loss: 0,
    groupIndex: 3,
    teamIndex: 12,
  },
];

export const groupD = [
  {
    name: "Francuska",
    rank: 51,
    points: 0,
    goalsScored: 0,
    goalsConceded: 0,
    goalDifference: 0,
    win: 0,
    draw: 0,
    loss: 0,
    groupIndex: 4,
    teamIndex: 13,
  },
  {
    name: "Peru",
    rank: 46,
    points: 0,
    goalsScored: 0,
    goalsConceded: 0,
    goalDifference: 0,
    win: 0,
    draw: 0,
    loss: 0,
    groupIndex: 4,
    teamIndex: 14,
  },
  {
    name: "Danska",
    rank: 20,
    points: 0,
    goalsScored: 0,
    goalsConceded: 0,
    goalDifference: 0,
    win: 0,
    draw: 0,
    loss: 0,
    groupIndex: 4,
    teamIndex: 15,
  },
  {
    name: "Tunis",
    rank: 10,
    points: 0,
    goalsScored: 0,
    goalsConceded: 0,
    goalDifference: 0,
    win: 0,
    draw: 0,
    loss: 0,
    groupIndex: 4,
    teamIndex: 16,
  },
];

export const groupE = [
  {
    name: "Spanija",
    rank: 7,
    points: 0,
    goalsScored: 0,
    goalsConceded: 0,
    goalDifference: 0,
    win: 0,
    draw: 0,
    loss: 0,
    groupIndex: 5,
    teamIndex: 17,
  },
  {
    name: "Novi Zeland",
    rank: 101,
    points: 0,
    goalsScored: 0,
    goalsConceded: 0,
    goalDifference: 0,
    win: 0,
    draw: 0,
    loss: 0,
    groupIndex: 5,
    teamIndex: 18,
  },
  {
    name: "Nemacka",
    rank: 12,
    points: 0,
    goalsScored: 0,
    goalsConceded: 0,
    goalDifference: 0,
    win: 0,
    draw: 0,
    loss: 0,
    groupIndex: 5,
    teamIndex: 19,
  },
  {
    name: "Japan",
    rank: 23,
    points: 0,
    goalsScored: 0,
    goalsConceded: 0,
    goalDifference: 0,
    win: 0,
    draw: 0,
    loss: 0,
    groupIndex: 5,
    teamIndex: 20,
  },
];

export const groupF = [
  {
    name: "Belgija",
    rank: 2,
    points: 0,
    goalsScored: 0,
    goalsConceded: 0,
    win: 0,
    draw: 0,
    loss: 0,
    goalDifference: 0,
    groupIndex: 6,
    teamIndex: 21,
  },
  {
    name: "Kanada",
    rank: 38,
    points: 0,
    goalsScored: 0,
    goalsConceded: 0,
    win: 0,
    draw: 0,
    loss: 0,
    goalDifference: 0,
    groupIndex: 6,
    teamIndex: 22,
  },
  {
    name: "Maroko",
    rank: 24,
    points: 0,
    goalsScored: 0,
    goalsConceded: 0,
    win: 0,
    draw: 0,
    loss: 0,
    goalDifference: 0,
    groupIndex: 6,
    teamIndex: 23,
  },
  {
    name: "Hrvatska",
    rank: 16,
    points: 0,
    goalsScored: 0,
    goalsConceded: 0,
    win: 0,
    draw: 0,
    loss: 0,
    goalDifference: 0,
    groupIndex: 6,
    teamIndex: 24,
  },
];

export const groupG = [
  {
    name: "Brazil",
    rank: 1,
    points: 0,
    goalsScored: 0,
    goalsConceded: 0,
    goalDifference: 0,
    win: 0,
    draw: 0,
    loss: 0,
    groupIndex: 7,
    teamIndex: 25,
  },
  {
    name: "Srbija",
    rank: 25,
    points: 0,
    goalsScored: 0,
    goalsConceded: 0,
    goalDifference: 0,
    win: 0,
    draw: 0,
    loss: 0,
    groupIndex: 7,
    teamIndex: 26,
  },
  {
    name: "Svajcarska",
    rank: 14,
    points: 0,
    goalsScored: 0,
    goalsConceded: 0,
    goalDifference: 0,
    win: 0,
    draw: 0,
    loss: 0,
    groupIndex: 7,
    teamIndex: 27,
  },
  {
    name: "Kamerun",
    rank: 37,
    points: 0,
    goalsScored: 0,
    goalsConceded: 0,
    goalDifference: 0,
    win: 0,
    draw: 0,
    loss: 0,
    groupIndex: 7,
    teamIndex: 28,
  },
];

export const groupH = [
  {
    name: "Portugal",
    rank: 8,
    points: 0,
    goalsScored: 0,
    goalsConceded: 0,
    goalDifference: 0,
    win: 0,
    draw: 0,
    loss: 0,
    groupIndex: 8,
    teamIndex: 29,
  },
  {
    name: "Gana",
    rank: 60,
    points: 0,
    goalsScored: 0,
    goalsConceded: 0,
    goalDifference: 0,
    win: 0,
    draw: 0,
    loss: 0,
    groupIndex: 8,
    teamIndex: 30,
  },
  {
    name: "Urugvaj",
    rank: 13,
    points: 0,
    goalsScored: 0,
    goalsConceded: 0,
    goalDifference: 0,
    win: 0,
    draw: 0,
    loss: 0,
    groupIndex: 8,
    teamIndex: 31,
  },
  {
    name: "Juzna Koreja",
    rank: 29,
    points: 0,
    goalsScored: 0,
    goalsConceded: 0,
    goalDifference: 0,
    win: 0,
    draw: 0,
    loss: 0,
    groupIndex: 8,
    teamIndex: 32,
  },
];
